config/routes.rb
Mybbs::Application.routes.draw do
  resources :posts

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mybbs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='navbar'>
  	<div class='navbar-inner'>
  		<div class='container-fluid'>
  			<a href='#' class='brand'>Mybbs</a>
  		</div>
  	</div> 
  </div>
  <div class='container-fluid'>
    <% flash.each do |name,msg| %>
      <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
        <a class='close' data-dismiss='alert'>x</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {class: 'form-vertical'}) do |f| %>
  <fieldset>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="controller-group">
      <%= f.label :title %>
      <div class="controls">
        <%= f.text_field :title, class: 'span12' %>
      </div>
    </div>
    <div class="controller-group">
      <%= f.label :body %>
      <div class="controls">
        <%= f.text_area :body, class: 'span12' %>
      </div>
    </div>
    <div class="form-actions clearfix">
      <span class='pull-right'>
        <%= link_to 'Back', posts_path, class: 'btn btn-small' %>
        <%= f.submit class: 'btn btn-primary' %>
      </span>
    </div>
  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<!-- <h1>Listing posts <%= link_to 'New Post', new_post_path, class: 'btn btn-small pull-right' %></h1> -->
<h1>Listing posts <a href='/posts/new' class='btn btn-action btn-small pull-right'><i class='icon-plus'></i> Add Post</a></h1>

<ul class='main-list well'>
<% @posts.each do |post| %>
  <li class='row-fluid'>
    <div class='span6'><%= post.title %></div>
    <!-- <span><%= post.body %></span> -->
    <div class='pull-right'>
      <!-- <%= link_to 'Show', post %> -->
      <!-- <%= link_to 'Edit', edit_post_path(post) %> -->
      <!-- <%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %> -->

      <a href="<%= post_path(post) %>" class='btn btn-mini'><i class='icon-zoom-in'></i></a>
      <a href="<%= edit_post_path(post) %>" class='btn btn-mini'><i class='icon-edit'></i></a>
      <a href="<%= post_path(post) %>" class='btn btn-danger btn-mini' data-confirm='Are you sure?' data-method='delete' rel='nofollow'><i class='icon-remove'></i></a>
    </div>
  </li>
<% end %>
</ul>
<br />

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %> <small><%= link_to 'Back', posts_path, class: 'btn pull-right btn-small' %></h1>

<%= simple_format(@post.body) %>